# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  system-check:
    build: system_check
    command: /system_check.sh
    privileged: true
    volumes:
      - ./output/:/output/
  tvs:
    depends_on:
      system-check:
        condition: service_completed_successfully
    build: tvs
    command: >
      ./tvs-server_main \
        --primary_private_key="0000000000000000000000000000000000000000000000000000000000000001" \
        --user_key_id=64 \
        --user_public_key="6f93de4039743e20e35120fca1af3222fa39ae3f7771f2bbbf82092c5004f938" \
        --user_secret="7c4fc15e7e4ac2b0095afcd7f514d6e9b6177cbec22b87c886d9dc85fbaf5bb2" \
        --user_authentication_public_key="043b5b650f59ec2905b1eed71eb48ffdc862acc1c0d3c6b5e46e8a0838060107e4e34cb2ace77a9f909d3a910430a61e2403e79492ea922ebe1162c0d86fb4afe0" \
        --port=7774 \
        --appraisal_policy_file='/appraisal_policy.prototext'
    volumes:
      - ./output/tvs-server_main:/tvs-server_main
      - ./conf/appraisal_policy.prototext:/appraisal_policy.prototext
    ports:
      - "7774:7774"
    networks:
      hats-dev:
        ipv4_address: 192.168.84.71
  workload-launcher:
    depends_on:
      - tvs
    build: launcher
    privileged: true
    command: ./launcher_main --tvs_addresses='localhost:7774' --use_tls=false --launcher_config_path='/config.prototext' --tvs_authentication_key='8f698f0b278cf57318a92faebb1dc49cda242973f2304e38660dc9bbc5cb18e5' --vmm_log_to_std --minloglevel=0 --stderrthreshold=0
    network_mode: "host"
    volumes:
      - ./output/launcher_main:/launcher_main
      - ./output/system_bundle.tar:/system_bundle.tar
      - ./conf/launcher_config.prototext:/config.prototext
      - ./output/workload.tar:/runc.tar
      - /tmp:/tmp

networks:
  hats-dev:
    name: hats-dev
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: hats-dev
    ipam:
      config:
        - subnet: 192.168.84.0/24
