bazel_dep(name = "protobuf", version = "26.0.bcr.1", repo_name = "com_google_protobuf")
bazel_dep(name = "grpc", version = "1.63.1", repo_name = "com_github_grpc_grpc")
bazel_dep(name = "rules_proto", version = "6.0.2", repo_name = "rules_proto")
bazel_dep(name = "rules_pkg", version = "0.9.1")
bazel_dep(name = "abseil-cpp", version = "20240116.2", repo_name = "com_google_absl")
bazel_dep(name = "rules_rust", version = "0.61.0")
git_override(
    module_name = "abseil-cpp",
    commit = "d9f501ef8482b3e6a41e3b544fde4569ad909c0b",
    remote = "https://github.com/abseil/abseil-cpp",
)
#bazel_dep(name = "rules_cc", version = "0.1.1")
