services:
  tvs:
    image: tvs:latest
    environment:
      USER_KEY_ID: 1 
      USER_PUBLIC_KEY: none
      USER_SECRET: 7c4fc15e7e4ac2b0095afcd7f514d6e9b6177cbec22b87c886d9dc85fbaf5bb2
      USER_AUTHENTICATION_PUBLIC_KEY: 043b5b650f59ec2905b1eed71eb48ffdc862acc1c0d3c6b5e46e8a0838060107e4e34cb2ace77a9f909d3a910430a61e2403e79492ea922ebe1162c0d86fb4afe0
      APPRAISAL_POLICY_FILE: /pv/appraisal_policy.txtpb 
    networks:
        - hats-compose
    volumes:
      - ./../workload/:/pv
  server1:
    image: launcher:latest
    cap_add:
      - NET_ADMIN
    environment:
      NO_SNP: true 
      SYSTEM_BUNDLE: /pv/system_bundle.tar 
      RUNC_RUNTIME_BUNDLE: /pv/runtime_bundle.tar 
      TVS_ADDRESSES: "hats-tvs:7774"
      TVS_AUTHENTICATION_KEY: 8f698f0b278cf57318a92faebb1dc49cda242973f2304e38660dc9bbc5cb18e5 
      NUM_CPUS: 1 
      RAMDRIVE_SIZE_KB: 1048576 
      RAM_SIZE_KB: 1048576 
    ports:
      - "8080:8080"
    devices:
      # - /dev/sev
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-vsock 
    networks:
      - hats-compose
    volumes:
      - ./../workload/:/pv
  server2:
    image: launcher:latest
    cap_add:
      - NET_ADMIN
    environment:
      NO_SNP: true 
      SYSTEM_BUNDLE: /pv/system_bundle.tar 
      RUNC_RUNTIME_BUNDLE: /pv/runtime_bundle.tar 
      TVS_ADDRESSES: hats-tvs:7774 
      TVS_AUTHENTICATION_KEY: 8f698f0b278cf57318a92faebb1dc49cda242973f2304e38660dc9bbc5cb18e5 
      NUM_CPUS: 1 
      RAMDRIVE_SIZE_KB: 1048576 
      RAM_SIZE_KB: 1048576 
    networks:
      - hats-compose
    volumes:
      - ./../workload/:/pv
    devices:
      # - /dev/sev
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-vsock 
networks:
  hats-compose:
      driver: bridge
      ipam:
        config:
          - subnet: 11.1.2.0/24
            gateway: 11.1.2.1
